nyc_parking_violations:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"  # Make sure this matches your Snowflake URL
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: parking_violations_dev
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_dev
      retry_on_database_errors: True
      retry_all: True
      connect_retries: 3
      connect_timeout: 30